name: Deploy to ECS

on:
  push:
    branches: [ arlerus ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::488453322320:role/github-actions-deployer
          aws-region: ap-southeast-2

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-southeast-2 \
            | docker login --username AWS --password-stdin 488453322320.dkr.ecr.ap-southeast-2.amazonaws.com

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=latest
          IMAGE_URI=488453322320.dkr.ecr.ap-southeast-2.amazonaws.com/${{ secrets.ECR_REPO }}:$IMAGE_TAG

          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Force ECS service to redeploy
        run: |
          aws ecs update-service \
            --cluster my-node-cluster \
            --service my-node-task-service \
            --force-new-deployment \
            --region ap-southeast-2
